### PR TITLE
Remove usage of deprecated `to_graphql`

### LINKED ISSUE #19: Broken in graphql-ruby 1.13+
`Legacy `.to_graphql` objects are deprecated and will be removed in GraphQL-Ruby 2.0. Remove `.to_graphql` to use a class-based definition instead.` 

This gem no longer works :(

### PR DESCRIPTION
**Pull request by dwillett**
## What

Closes #19. As far as I can tell `GraphQL::Schema.types` now exposes the equivalent.

### CODE REVIEW

**Review by ppascualv — APPROVED** [review]

**Comment by ppascualv** [comment]
Could anyone merge this PR?

**Comment by dwillett** [comment]
@benrbrook do you still have write access to this repo? 

Otherwise, @Kjentleman @jacobmoretti @crempp - hi! Could one of you help get this merged?

**Comment by jacobmoretti** [comment]
@dwillett Hey Dave, I'll get this merged and a minor version release out for this fix today.

**Comment by jacobmoretti** [comment]
@dwillett Looks like the 30 day window for the github action to run CI expired. Are you able to push a new commit or re-open the PR? I believe that should re-trigger it. I'd like to make sure that passes before merging.

**Review by jacobmoretti — APPROVED** [review]
Thanks for making the changes to get Rubocop to pass.

**Comment by dwillett** [comment]
Awesome, thanks Jacob!

**Comment by benrbrook** [comment]
Thanks for taking care of this. Sorry I missed the original issue!

**Pull request merged**
